version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mini_crm_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mini_crm
      TZ: Asia/Tashkent
    command: ["--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    container_name: mini_crm_admin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:password@db:3306/mini_crm
      SESSION_SECRET: ${SESSION_SECRET:-replace-with-strong-random-string}
      TZ: Asia/Tashkent
      PORT: 3000
    ports:
      - "127.0.0.1:3000:3000"

  pos:
    build:
      context: .
      dockerfile: apps/pos/Dockerfile
    container_name: mini_crm_pos
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:password@db:3306/mini_crm
      SESSION_SECRET: ${SESSION_SECRET:-replace-with-strong-random-string}
      TZ: Asia/Tashkent
      PORT: 4000
    ports:
      - "127.0.0.1:4000:4000"

  bot:
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    container_name: mini_crm_bot
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:password@db:3306/mini_crm
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_ALLOWED_IDS: ${TELEGRAM_ALLOWED_IDS}
      TZ: Asia/Tashkent

volumes:
  db_data:
